# Copyright 2022 flashcat.cloud | 快猫星云
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- if eq .Values.nwebapi.type "internal" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwebapi-alerts
data:
  mysql_by_exporter.json: |-
    [
        {
          "name": "MysqlInnodbLogWaits",
          "note": "MySQL innodb log writes stalling",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "rate(mysql_global_status_innodb_log_waits[15m]) > 10",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlInnodbLogWaits"
          ]
        },
        {
          "name": "MysqlSlaveIoThreadNotRunning",
          "note": "MySQL Slave IO thread not running",
          "severity": 1,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_io_running == 0",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlSlaveIoThreadNotRunning"
          ]
        },
        {
          "name": "MysqlSlaveReplicationLag",
          "note": "",
          "severity": 1,
          "disabled": 0,
          "prom_for_duration": 60,
          "prom_ql": "mysql_slave_status_master_server_id > 0 and ON (instance) (mysql_slave_status_seconds_behind_master - mysql_slave_status_sql_delay) > 30",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlSlaveReplicationLag"
          ]
        },
        {
          "name": "MysqlSlaveSqlThreadNotRunning",
          "note": "MySQL Slave SQL thread not running",
          "severity": 1,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_sql_running == 0",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlSlaveSqlThreadNotRunning"
          ]
        },
        {
          "name": "Mysql刚刚有重启，请注意",
          "note": "MySQL has just been restarted, less than one minute ago",
          "severity": 3,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "mysql_global_status_uptime < 60",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlRestarted"
          ]
        },
        {
          "name": "Mysql实例挂了",
          "note": "",
          "severity": 1,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "mysql_up == 0",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlDown"
          ]
        },
        {
          "name": "Mysql打开了很多文件句柄，请注意",
          "note": "More than 80% of MySQL files open",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 120,
          "prom_ql": "avg by (instance) (mysql_global_status_innodb_num_open_files) / avg by (instance)(mysql_global_variables_open_files_limit) * 100 > 80",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlHighOpenFiles"
          ]
        },
        {
          "name": "Mysql最近一分钟有慢查询出现",
          "note": "MySQL server mysql has some new slow query",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 120,
          "prom_ql": "increase(mysql_global_status_slow_queries[1m]) > 0",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlSlowQueries"
          ]
        },
        {
          "name": "Mysql有超过60%的连接是running状态",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 120,
          "prom_ql": "avg by (instance) (mysql_global_status_threads_running) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 60",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlHighThreadsRunning"
          ]
        },
        {
          "name": "Mysql连接数已超过80%",
          "note": "More than 80% of MySQL connections are in use",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 120,
          "prom_ql": "avg by (instance) (mysql_global_status_threads_connected) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=MysqlTooManyConnections"
          ]
        }
    ]
  redis_by_exporter.json: |-
    [
        {
          "name": "Redis内存使用率较高",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 60,
          "prom_ql": "redis_memory_max_bytes > 0 and (redis_memory_used_bytes / redis_memory_max_bytes) > 0.85",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisHighMemoryUsage"
          ]
        },
        {
          "name": "Redis出现拒绝连接",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "(rate(redis_rejected_connections_total[5m])) > 0",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisRejectedConnHigh"
          ]
        },
        {
          "name": "Redis刚刚有重启，请注意",
          "note": "",
          "severity": 3,
          "disabled": 0,
          "prom_for_duration": 0,
          "prom_ql": "redis_uptime_in_seconds < 600",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisLowUptime"
          ]
        },
        {
          "name": "Redis客户端连接数过高",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 60,
          "prom_ql": "(redis_connected_clients / redis_config_maxclients) > 0.85",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisHighClientsUsage"
          ]
        },
        {
          "name": "Redis延迟高",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 60,
          "prom_ql": "sum(rate(redis_commands_duration_seconds_total[5m])) / sum(rate(redis_commands_processed_total[5m])) > 0.25",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisHighResponseTime"
          ]
        },
        {
          "name": "Redis较低的命中率",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 60,
          "prom_ql": "rate(redis_keyspace_hits_total[5m])\n/\n(rate(redis_keyspace_misses_total[5m]) + rate(redis_keyspace_hits_total[5m]))\n< 0.9",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisLowHitRatio"
          ]
        },
        {
          "name": "Redis驱逐率较高",
          "note": "",
          "severity": 2,
          "disabled": 0,
          "prom_for_duration": 60,
          "prom_ql": "(sum(rate(redis_evicted_keys_total[5m])) / sum(redis_db_keys)) > 0.1",
          "prom_eval_interval": 15,
          "enable_stime": "00:00",
          "enable_etime": "23:59",
          "enable_days_of_week": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "0"
          ],
          "enable_in_bg": 0,
          "notify_recovered": 1,
          "notify_channels": [],
          "notify_repeat_step": 60,
          "recover_duration": 0,
          "callbacks": [],
          "runbook_url": "",
          "append_tags": [
            "alertname=RedisHighKeysEvictionRatio"
          ]
        }
    ]
{{- end -}}
