{{/*
# Copyright 2022 flashcat.cloud | 快猫星云
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
*/}}
{{- if eq .Values.nwebapi.type "internal" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwebapi-config
data:
  metrics.yaml: |-
{{ .Files.Get "metrics/metrics.yaml" | indent 4 }}
  webapi.conf: |-
    RunMode = "release"
    MetricsYamlFile = "/app/etc/metrics.yaml"
    BuiltinAlertsDir = "/app/etc/alerts"
    BuiltinDashboardsDir = "/app/etc/dashboards"
    [[NotifyChannels]]
    Label = "邮箱"
    Key = "email"
    [[NotifyChannels]]
    Label = "钉钉机器人"
    Key = "dingtalk"
    [[NotifyChannels]]
    Label = "企微机器人"
    Key = "wecom"
    [[NotifyChannels]]
    Label = "飞书机器人"
    Key = "feishu"
    [[ContactKeys]]
    Label = "Wecom Robot Token"
    Key = "wecom_robot_token"
    [[ContactKeys]]
    Label = "Dingtalk Robot Token"
    Key = "dingtalk_robot_token"
    [[ContactKeys]]
    Label = "Feishu Robot Token"
    Key = "feishu_robot_token"
    [Log]
    Dir = "logs"
    Level = "DEBUG"
    Output = "stdout"
    [HTTP]
    Host = "0.0.0.0"
    Port = {{ template "nightingale.nwebapi.port" . }}
    CertFile = ""
    KeyFile = ""
    PrintAccessLog = true
    PProf = false
    ShutdownTimeout = 30
    MaxContentLength = 67108864
    ReadTimeout = 20
    WriteTimeout = 40
    IdleTimeout = 120
    [JWTAuth]
    SigningKey = "5b94a0fd640fe2765af826acfe42d151"
    AccessExpired = 1500
    RefreshExpired = 10080
    RedisKeyPrefix = "/jwt/"
    [BasicAuth]
    user001 = "ccc26da7b9aba533cbb263a36c07dcc5"
    [AnonymousAccess]
    PromQuerier = false
    AlertDetail = false
    [LDAP]
    Enable = false
    Host = "ldap.example.org"
    Port = 389
    BaseDn = "dc=example,dc=org"
    BindUser = "cn=manager,dc=example,dc=org"
    BindPass = "*******"
    AuthFilter = "(&(uid=%s))"
    CoverAttributes = true
    TLS = false
    StartTLS = true
    DefaultRoles = ["Standard"]
    [LDAP.Attributes]
    Nickname = "cn"
    Phone = "mobile"
    Email = "mail"
    [OIDC]
    Enable = false
    RedirectURL = "http://n9e.com/callback"
    SsoAddr = "http://sso.example.org"
    ClientId = ""
    ClientSecret = ""
    CoverAttributes = true
    DefaultRoles = ["Standard"]
    [OIDC.Attributes]
    Nickname = "nickname"
    Phone = "phone_number"
    Email = "email"
    [Redis]
    Address = "{{ template "nightingale.redis.addr" . }}"
    Password = "{{ template "nightingale.redis.password" . }}"
    [DB]
    DSN = "{{ template "nightingale.database.username" . }}:{{ template "nightingale.database.rawPassword" . }}@tcp({{ template "nightingale.database.host" . }}:{{ template "nightingale.database.servicePort" . }})/{{ template "nightingale.database.name" . }}?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
    Debug = true
    DBType = "mysql"
    MaxLifetime = 7200
    MaxOpenConns = 150
    MaxIdleConns = 50
    TablePrefix = ""
    [[Clusters]]
    Name = "Default"
    Prom = "http://{{ template "nightingale.prometheus.host" . }}:{{ template "nightingale.prometheus.servicePort" .}}"
    BasicAuthUser = ""
    BasicAuthPass = ""
    Timeout = 30000
    DialTimeout = 10000
    TLSHandshakeTimeout = 30000
    ExpectContinueTimeout = 1000
    IdleConnTimeout = 90000
    KeepAlive = 30000
    MaxConnsPerHost = 0
    MaxIdleConns = 100
    MaxIdleConnsPerHost = 100
    [Ibex]
    Address = "http://ibex:10090"
    BasicAuthUser = "ibex"
    BasicAuthPass = "ibex"
    Timeout = 3000
{{- end -}}
