{{- if eq (include "nightingale.autoGenCertForIngress" .) "true" }}
{{- $ca := genCA "nightingale-ca" 365 }}
{{- $cert := genSignedCert .Values.expose.ingress.hosts.web nil (list .Values.expose.ingress.hosts.web) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "nightingale.ingress" . }}"
  labels:
{{ include "nightingale.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}