{{/*
# Copyright 2022 flashcat.cloud | 快猫星云
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
*/}}
{{- if eq (include "nightingale.autoGenCertForIngress" .) "true" }}
{{- $ca := genCA "nightingale-ca" 365 }}
{{- $cert := genSignedCert .Values.expose.ingress.hosts.web nil (list .Values.expose.ingress.hosts.web) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "nightingale.ingress" . }}"
  labels:
{{ include "nightingale.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}